import { computed, ComputedRef, ref } from 'vue'
import { collection, getFirestore, onSnapshot, orderBy, query, addDoc } from '@firebase/firestore'
import { useAuth } from '../authz'
import { SiteData, Site } from '@/state/site/Site'

const fullSiteList = ref(new Map<string, Site>())

const allSites = computed(() => {
  const sites = Array.from(fullSiteList.value.values())
  return sites
})

const publicSites = computed(() => {
  const sites = Array.from(fullSiteList.value.values()).filter((a) => (!a.hidden))
  sites.sort((a, b) => (a.compareChangeTime(b)))
  return sites
})

const userSites = computed(() => {
  const sites = Array.from(fullSiteList.value.values())
  const { user } = useAuth()
  const uid = user.value.uid
  const filteredSites = sites.filter((a) => (a.canEdit(uid)))
  return filteredSites
})

const visibleSites = computed(() => {
  const { user } = useAuth()
  return allSites.value.filter((val) => (
    !val.hidden ||
    val.canEdit(user.value.uid)
  ))
})

let _init = false
let unsubscribe = () => {}

async function subscribeToSites () {
  unsubscribe()
  const db = getFirestore()
  const q = query(collection(db, 'sites'), orderBy('lastUpdate', 'desc'))
  unsubscribe = onSnapshot(q, (snap) => {
    snap.docChanges().forEach((change) => {
      fullSiteList.value.set(change.doc.id, new Site(change.doc.id, change.doc.data()))
    })
  })
}

export function sortByLastUpdate (a:Site, b:Site): number {
  if (a.lastUpdate && b.lastUpdate) {
    return a.lastUpdate.seconds < b.lastUpdate.seconds ? 1 : -1
  }
  return 0
}

export async function createSite (data: SiteData): Promise<string> {
  const { user } = useAuth()

  data.owners = [user.value.uid]

  const site = new Site(data.id, data)
  // Flush the id field for now. It will be generated by addDoc, and filled by fetch/subscribe for the entity used by the UI
  site.id = ''

  const sitedoc = await addDoc(
    collection(
      getFirestore(),
      'sites'
    ),
    site.toJSON()
  )

  return sitedoc.id
}

export function useSites (): {
    publicSites: ComputedRef<Array<Site>>,
    allSites: ComputedRef<Array<Site>>,
    userSites: ComputedRef<Array<Site>>,
    visibleSites: ComputedRef<Array<Site>>,
    } {
  if (!_init) {
    subscribeToSites()
    _init = true
  }
  return { publicSites, allSites, userSites, visibleSites }
}
